openapi: 3.0.3
info:
  title: KIV/PIA REST API
  description: blah
  version: 0.0.1
tags:
  - name: Hello
    description: blah
  - name: Damage
    description: blah
paths:
  /hello:
    get:
      tags:
        - Hello
      summary: Says hello on behalf of given user
      operationId: sayHello
      parameters:
        - name: from
          in: query
          description: blah
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            text/html:
              schema:
                type: string
                example: Hello World from Pavel!
        '405':
          description: Not supported HTTP method.
        '406':
          description: Not acceptable response representation.
  /damages:
    post:
      tags:
        - Damage
      summary: Creates a new damage report
      operationId: createDamage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DamageDTO"
        required: true
      responses:
        '201':
          description: Damage report was successfully created.
        '400':
          description: Request body is not formatted correctly.
        '403':
          description: Current user is not authorized to report damage.
        '405':
          description: Unsupported HTTP method.
        '406':
          description: Not acceptable response representation.
        '500':
          description: Server error.
    get:
      tags:
        - Damage
      summary: Retrieves all damage currently stored in the system visible for the current user
      operationId: retrieveDamage
      responses:
        '200':
          description: Damage reports are retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DamageDTO'
        '405':
          description: Not supported HTTP method.
        '406':
          description: Not acceptable response representation.
        '500':
          description: Server error.
components:
  schemas:
    DamageDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        impaired:
          $ref: '#/components/schemas/ImpairedUserDTO'
        timestamp:
          type: string
          format: date-time
        location:
          $ref: '#/components/schemas/LocationDTO'
        description:
          type: string
          example: "Lorem ipsum"
      required:
        - impaired
        - timestamp
        - location
        - description
    ImpairedUserDTO:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        emailAddress:
          type: string
          example: "john.doe@example.com"
      required:
        - name
        - emailAddress
    LocationDTO:
      type: object
      properties:
        longitude:
          type: number
          format: double
          example: "49.7269708"
        latitude:
          type: number
          format: double
          example: "13.3516872"
      required:
        - longitude
        - latitude
